# Build stage
FROM maven:3.9.6-eclipse-temurin-25 AS build
WORKDIR /app

# Copiamos solo pom primero para cachear dependencias
COPY pom.xml .
RUN mvn dependency:go-offline

# Ahora copiamos el resto
COPY src ./src
RUN mvn clean package -DskipTests

# Runtime stage
FROM eclipse-temurin:25-jdk
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]