name: Publish to GitHub Container Registry

on:
  push:
    branches: [main]

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
        steps:
            - name: Check out the repository
              uses: actions/checkout@v3

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Convert repository name to lowercase
              id: repo
              run: echo "name=${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"

            - name: Build and push Docker image
              uses: docker/build-push-action@v3
              with:
                context: ./backend
                file: ./backend/docker/Dockerfile.compile
                push: true
                tags: ghcr.io/${{ steps.repo.outputs.name }}-backend:latest